# Generated by Django 4.1.5 on 2023-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
                ('escolha', models.CharField(choices=[('A', 'Vou Escrever'), ('L', 'Vou Apenas Ler')], default='L', max_length=1)),
            ],
        ),
    ]
