# Generated by Django 4.1.5 on 2023-01-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='escolha',
        ),
    ]
