# Generated by Django 4.1.5 on 2023-01-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0002_remove_usuario_escolha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='choices',
            field=models.CharField(choices=[('L', 'Vou Ler'), ('V', 'Vou Escrever')], default='L', max_length=1),
        ),
    ]
