# Generated by Django 4.1.5 on 2023-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0003_usuario_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='choices',
            field=models.CharField(choices=[('L', 'Vou Ler'), ('E', 'Vou Escrever')], default='L', max_length=1),
        ),
    ]
