# Generated by Django 4.1.5 on 2023-01-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0004_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo_usuario',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminio')], default=('M', 'Masculino'), max_length=1, null=True),
        ),
    ]
