# Generated by Django 4.1.5 on 2023-01-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0004_alter_usuario_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='choices',
            new_name='tipo',
        ),
    ]
