# Generated by Django 4.1.5 on 2023-01-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0005_rename_choices_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('L', 'Vou Ler'), ('E', 'Vou Escrever')], max_length=1),
        ),
    ]
