# Generated by Django 4.1.5 on 2023-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0006_alter_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='escolha',
            field=models.BooleanField(default=False),
        ),
    ]
