# Generated by Django 4.1.5 on 2023-01-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0006_rename_tipo_usuario_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Administrador'), ('AU', 'Autor'), ('CO', 'Comum')], max_length=2),
        ),
    ]
