# Generated by Django 4.1.5 on 2023-01-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0007_remove_usuario_tipo_usuario_escolha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='escolha',
            new_name='autor',
        ),
    ]
