# Generated by Django 4.1.5 on 2023-01-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0008_rename_escolha_usuario_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=64)),
            ],
        ),
    ]
