# Generated by Django 4.1.5 on 2023-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0009_usuarioadm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioAdm',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='autor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('AD', 'Administrador'), ('AU', 'Autor'), ('CO', 'Comum')], default='Administrador', max_length=30),
        ),
    ]
