# Generated by Django 4.1.5 on 2023-01-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
