# Generated by Django 4.1.5 on 2023-01-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=15),
        ),
    ]
