# Generated by Django 4.1.5 on 2023-01-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0003_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
