# Generated by Django 4.1.5 on 2023-01-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0008_alter_post_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
    ]
