# Generated by Django 4.1.5 on 2023-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0010_comentário'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='Sem imagem', upload_to='img_principal'),
        ),
    ]
