# Generated by Django 4.1.5 on 2023-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0011_alter_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='settings.MEDIA_ROOT/media/img_principal/sem-img.jpg', upload_to='img_principal'),
        ),
    ]
