# Generated by Django 4.1.5 on 2023-01-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0008_alter_usuario_options'),
        ('Postagem', '0013_alter_post_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentário',
            new_name='Comentario',
        ),
    ]
