# Generated by Django 4.1.5 on 2023-01-16 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postagem', '0014_rename_comentário_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_coment',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
