# Generated by Django 4.1.5 on 2023-01-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfilUser', '0008_alter_usuario_options'),
        ('Postagem', '0015_comentario_data_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='perfilUser.usuario'),
        ),
    ]
