# Generated by Django 4.1.5 on 2023-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilAdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadm',
            name='choice',
            field=models.CharField(choices=[('A', 'Autor'), ('M', 'Administrador')], default='A', max_length=1),
        ),
    ]
